### PR TITLE
Clean up remaining `clippy` warnings

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This small PR just cleans up the remaining `clippy` warnings in the repository.

As the PR is based on #91 it is preferably rebased on top of main after that one is merged. It would also be nice to squash all of these commits into one commit before merge :nerd_face:

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test-manager/src/vm/network/macos.rs` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93#-N_D5b86A1e4oIyDPhGL:-N_D5b870IlWRfMI2uqm:besq7f5) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/9919dc892ed4eb4f5771f5e351ebde9f0589b922/test-manager/src/vm/network/macos.rs#L28)):*
> ```XML
> /// "Real" (non-tunnel) IP of the wireguard remote peer as defined in `setup-network.sh`.
> /// TODO: This should not be hardcoded. Set by tart.
> pub const CUSTOM_TUN_REMOTE_REAL_ADDR: Ipv4Addr = Ipv4Addr::new(192, 168, 64, 1);
> ```

These are used on macOS, so we cannot remove them. But we probably don't need to compile this on Linux.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test-manager/src/vm/network/macos.rs` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93#-N_D5b86A1e4oIyDPhGL:-NaeuKhC-aLhgVrpO5fw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/9919dc892ed4eb4f5771f5e351ebde9f0589b922/test-manager/src/vm/network/macos.rs#L28)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

These are used on macOS, so we cannot remove them. But we probably don't need to compile this on Linux.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

**Review by dlon — CHANGES_REQUESTED** [review]
Does not compile on macOS.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93#-:-NbJVPpvCaNSYlkJoJM1:bx8jbk0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

**Review by dlon — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

**Pull request merged**
