### PR TITLE
Improve `e2e-test missing` error by adding context

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Previously, if no "matching" e2e test was found for a package-under-test, the error logging would not indicate that it was due to the test-runner failing to find the e2e-teset binary. Instead, it would just print `Could not find package ..`, which is more general and not that helpful in this case.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/package.rs` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80#-NZROkrhAm8G63GH02Hv:-NZaDnj741d_nhU-XVqr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/ba816d86d2ad2b79b93497ceeb800ef24bc0d34b/test-manager/src/package.rs#L41)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't think that this can actually fail unless the regex is wrong, as `captures` would have returned `None`. Since we know at compile-time that it cannot fail (unless there is a bug), it is probably better to call `unwrap` or `expect` rather than return an error.

I'd also suggest changing the message. We're not failing to find the test runner here. We're failing to parse the version out of the app file name.
</blockquote></details>

Done.
___
*[`test-manager/src/package.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80#-NZRMz6U8Hxn7k2lrCeT:-NZaDoiaCZTRtP7udSHe:bo5jtj0) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/ba816d86d2ad2b79b93497ceeb800ef24bc0d34b/test-manager/src/package.rs#L139)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Since this function already knows about `e2e_bin`, I think that the new, much better error message (the second one above) should be returned here instead of at the call site. :slightly_smiling_face: 
</blockquote></details>

I think I refactored the code into how you suggested, but please cross-check me on that :blush:

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test-manager/src/package.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80#-NZRMz6U8Hxn7k2lrCeT:-NZacIti8rzQFnmCWGqI:b6ilfni) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/ba816d86d2ad2b79b93497ceeb800ef24bc0d34b/test-manager/src/package.rs#L139)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think I refactored the code into how you suggested, but please cross-check me on that :blush: 
</blockquote></details>

Not exactly. This error is only correct if `e2e_bin` is true. We should have different error messages depending on that.

Something like this might be ok:

```rust
matches.into_iter().next().with_context(|| {
    if e2e_bin {
        format!("TODO")
    } else {
        format!("TODO")
    }
})
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test-manager/src/package.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80#-NZRMz6U8Hxn7k2lrCeT:-NZe0r8qE7uCJQ7_9jYL:b-40022f) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/ba816d86d2ad2b79b93497ceeb800ef24bc0d34b/test-manager/src/package.rs#L139)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not exactly: This error is only correct if `e2e_bin` is true. We should have different error messages depending on that.

Something like this might be ok:

```rust
matches.into_iter().next().with_context(|| {
    if e2e_bin {
        format!("TODO")
    } else {
        format!("TODO")
    }
})
```
</blockquote></details>

Ah, I see! If `e2e_bin` was not considered here, I would have introduced some new confusion :sweat_smile: 

Fixed!

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/80#-:-NZeFkUG7g0Ce9iQ6Dct:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

**Pull request merged**
