### PR TITLE
Add more eye candy to test results HTML output

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Make the test output HTML easier to parse at a glance by adding some distinct icons/colors to distinguish the result of each test, as well as a counter for displaying the ratio between passing tests & the total number of test.

### Some test(s) failed
image

### All tests passed
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
This looks great :)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97#-:-NbEIqkL2CBcSkvAyPEu:bqxx2bv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test-manager/src/summary.rs` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97#-NbJ93Pl-gWScYwWbpvA:-NbJ93Pl-gWScYwWbpvB:bb752ax) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/cbc916f664dee2c86ae19716446b12fe19f3f1c5/test-manager/src/summary.rs#L30)):*
> ```XML
>     const PASS_STR: &str = "✅";
>     const FAIL_STR: &str = "❌";
>     const UKNNOWN_STR: &str = " ";
> ```

Typo

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test-manager/src/summary.rs` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97#-NbJ93Pl-gWScYwWbpvA:-NbJCmNw8hc8LwFQjIUY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/cbc916f664dee2c86ae19716446b12fe19f3f1c5/test-manager/src/summary.rs#L30)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

**Pull request merged**
